### ISSUE TITLE
Same filename with different casing

### ISSUE THREAD

**Issue by adius** [Balatzar/InstaGroot#9]
Hi, I'm just curious why the `node_modules` directory contains files with the same name but different casing?
E.g. https://github.com/Balatzar/InstaGroot/blob/master/node_modules/body-parser/HISTORY.md and https://github.com/Balatzar/InstaGroot/blob/master/node_modules/body-parser/History.md

I just cloned the repo and a lot of things broke, because MacOS is case insensitive and therefore
they appeared to be the same files to it. 🙈

Thanks for your help!

**Comment by Balatzar** [comment]
Hey ! :D

Woah this was our first MEAN project in school a few months ago! Feels weird to get back into it but I  like it a lot ^^

So I don't know why there was the same file with different casing, but i committed a version without the node module so you cant just do a `npm install` and a `node server.js` and it should work :)
 Don't hesitate to tell me if there are any other issues !

**Comment by adius** [comment]
Well, to be honest I'm not interested in your project per se. 😅
I write a program to analyze git repos and randomly tried to analyze yours
but the casing issue crashed my whole program.
Now I'm wondering if I have to handle this special case better or if it's just a one in a million thing…
That's why it would be super helpful to know why those files were created in the first place.
Thanks for your help! 😊

**Comment by Balatzar** [comment]
Yeah i figured :smile:

Yeah it's quite weird because when I install it with `npm install` the file is named "History.md", but [here](https://github.com/expressjs/body-parser/blob/master/HISTORY.md) it's in caps.

**Comment by Balatzar** [comment]
I'm on linux

**Comment by adius** [comment]
> I'm on linux

I figured ;-)

Mh, really weird. I'll just ignore this for now as a one in a million thing =D
If you ever get an idea why this might happen, make sure to give me a heads up!
The production version will run on linux anyways so I guess this won't be a problem then…
